print("Enter the value of 'a' and 'b' for a(b^2) equation")
a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
equation=a*(b**2)
print("The output of equation is: ",equation)
